name: flutter_absensi
description: "PeopleSync Mobile - Employee Attendance App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.8
  
  # Network
  dio: ^5.4.0
  connectivity_plus: ^6.0.3
  
  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  
  # Navigation
  go_router: ^14.2.0
  
  # Storage
  flutter_secure_storage: ^9.2.2
  
  # Location
  geolocator: ^12.0.0
  
  # Utils
  intl: ^0.19.0
  flutter_dotenv: ^5.1.0
  
  # Data Classes
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
  # Code Generation
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true
  
  assets:
    - .env
